### ISSUE TITLE
TRAINING ERROR

### ISSUE THREAD

**Issue by x4jc1** [alirezatwk/Convolutional-Neural-Network-Based-Image-Watermarking-using-Discrete-Wavelet-Transform#2]
hi~ here i meet the error:
Input to reshape is a tensor with 265600 values, but the requested shape has 65536
could u pls explain the reasons for this?

**Comment by x4jc1** [comment]
> hi~ here i meet the error: Input to reshape is a tensor with 265600 values, but the requested shape has 65536 could u pls explain the reasons for this?

**Comment by x4jc1** [comment]
hi~
I resized coco images to size 256*256 before training. but i'm not sure if it will work.

**Comment by 3254657307** [comment]
Did you run it successfully?

**Comment by 3254657307** [comment]
ValueError: 'images' must have either 3 or 4 dimensions.

**Comment by alirezatwk** [comment]
> hi~ here i meet the error: Input to reshape is a tensor with 265600 values, but the requested shape has 65536 could u pls explain the reasons for this?

Hi.
We hard coded the size of input image in the JPEGAttack class. However, the hard coded size is not necessary. You can change it by yourself.

Resizing the input images to 256x256 would be fine.
